apiVersion: v1
kind: Service
metadata:
  name: frontend-app-svc
  namespace: app
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - name: http
      nodePort: 30001
      port: 30001
      targetPort: 80
